name: nop_db_sqflite
description: nop_db sqflite implemention
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop_db:
    git:
      url: https://github.com/sersr/nop_db.git
  nop_annotations: ">=0.2.0 <0.3.0"
  sqflite: ">=2.0.1 <3.0.0"
  sqflite_common_ffi: ">=2.1.0 <3.0.0"
  nop: ">=0.0.3+1 <1.0.0"

dependency_overrides:
  nop:
    path: ../nop
  nop_gen:
    path: ../nop_gen
  nop_db:
    path: ../nop_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  nop_gen: ^0.2.1+2
