name: nop_db_sqflite
description: nop_db sqflite implemention
version: 0.0.3
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop:
    git:
      url: https://github.com/sersr/nop.git
  sqflite: ^2.0.1
  sqflite_common_ffi: ^2.1.0

dependency_overrides:
  nop:
    path: ../nop
  nop_gen:
    path: ../nop_gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  nop_gen:
    git:
      url: https://github.com/sersr/nop_gen.git